[platformio]
default_envs = klipper

[env:klipper]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git#95685b9bb8469bdc0d7901065b677002e2d9156c
framework = noneos-sdk
board = genericCH32V203C8T6
board_upload.maximum_size = 61440
build_type = release
board_build.use_lto = yes
board_build.use_builtin_debug_code = no
board_build.cpp_support = yes
build_flags =
  -DSYSCLK_FREQ_144MHz_HSI=144000000
  -DBMCU_KLIPPER_MODE=1
  -DBAMBU_BUS_AMS_NUM=0
  -DBMCU_ONLINE_LED_FILAMENT_RGB=1
  -DBMCU_DM_TWO_MICROSWITCH=1
  -DBMCU_UART_BAUD=115200
